### ISSUE TITLE
DOCUMENTATION: Icons

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ux#294] opened 2017-03-03 01:53 UTC
The development team has requested that all of the current icons listed in the visual design spec sheets be compiled into one sheet for ease of reference. This will help to deter the random use of icons for defined states, as well as mismatches between Font Awesome and PatternFly.

In Addition, some testing will be done with [VISUALS (TESTING): Status Icons](https://github.com/fabric8io/fabric8-ux/issues/299)

**Comment by mindreeper2420** [comment] 2017-03-03 01:55
So far, the following icons have been located:

- [Icons for Types and States](https://redhat.invisionapp.com/share/6PAFLW2AJ#/211446631_A-0100)
- [Warning Triangle](https://redhat.invisionapp.com/share/FR9R8G6B9#/214418045_A-0670-Iterations_-_Future_Open)
- [Add Work Item: Work Item Detail Panel](https://redhat.invisionapp.com/share/DF8ZQ11R7#/196006933_A-000)

**Comment by bdellasc** [comment] 2017-03-03 16:03
I met briefly with @jryhanyc and I'll set up a template with the icons I've used thus far, then post it to InVision. When she has created her icons, she'll add to the file.

**Comment by mindreeper2420** [comment] 2017-03-03 16:07
sounds good. If there are new icons/fonts, we could possibly add those to the Platform/Planner first, and then create a PR for PatternFly. There has been talk about integrating pieces from this project to PatternFly, so that might be a good first piece.

**Comment by bdellasc** [comment] 2017-03-03 16:21
I like that idea, thanks!

**Comment by mindreeper2420** [comment] 2017-03-06 11:57
@bdellasc @jryhanyc I'll be updating the backend code with the correct icons (that is where the UI gets them from), so once they are ready to go, just let me know. If they are being done in parts, I can create multiple PRs for them to consume to match our Sprints :-)

**Comment by bdellasc** [comment] 2017-03-06 22:49
@qodfathr, @michaelkleinhenz, @michaelvirgil, @maxandersen, @Mgranfie 

For the Issue Tracking & Scrum Work Item types, we referred to [this spreadsheet](https://docs.google.com/a/redhat.com/spreadsheets/d/1iQ3MBitXy5zWAvxWzHQKtXuv5SWs_uUCQvrqngfm5K8/edit?usp=sharing) and pieced together from mockups @mindreeper2420 mentioned above. Two of the four templates (Agile? & Scenario-Driven?) are not yet listed here as they are still being sorted out.

I posted mockups of all the icons we're aware of across [3 InVision mockups](https://redhat.invisionapp.com/share/HBAQIPL96). 

For the "Work Item Types" (page 1), there are questions:
- Is "Feature" part of the "Scenario-Driven" methodology?
- If the red items are still needed, are they listed under the correct methodology?
- Do we have any of the other missing Work Item Types nailed down yet?
- Are there Work Item Types that belong to multiple methodologies?

Can someone please provide definitions for the Work Item Types currently without icons (and not included in the [PDD Glossary](https://docs.google.com/a/redhat.com/document/d/1bMq-C_Xb1DZ0LIpUmCPiN1O9MuDvnUex9D8YFAG8wOg/edit?usp=sharing) ) I did some web searches and here was what I found:
- Task: a piece of work that needs to be completed for a story?
- Issue: something that has already happened and is entered into the system?
- Any other Work Item Types that still need to be added to the list

Additional stories blocked by these open issues:
- [Map Statuses & Types to iconography + create iconography (Part 1 of 2)](https://github.com/fabric8io/fabric8-ux/issues/215)
- [VISUALS (SPECS): Map Statuses & Types to iconography + create iconography (Part 2 of 2)](https://github.com/fabric8io/fabric8-ux/issues/215)

**Comment by bdellasc** [comment] 2017-03-09 18:30
Current (unconfirmed) types & states:
Issue Tracking
———————————————
Issue
New
Active (= In Progress)
Resolved (= Done) 
Closed (verified and meets the Definition of Done)
Removed (= Deleted, for now)

Task
New
Active
Closed
Removed

Model: Scrum
———————————————
**Bug, Product Backlog Item**
New
Approved (approved by PM or Ready-Ready, and can planed or handed off the the team.)
Committed (team has planned to work on it)
In Progress
Done
Closed
Removed

**Task**
To Do
In Progress
Done
Removed

**Epic & Feature**
New
In Progress
Done
Removed

**Comment by bdellasc** [comment] 2017-03-10 16:36
@jryhanyc - waiting on two definitions. I sent an e-mail.

**Comment by bdellasc** [comment] 2017-03-16 14:24
@jryhanyc, I updated the top section with the latest definitions and additional work item types.

**Comment by bdellasc** [comment] 2017-03-20 14:05
Closing this, since there is a visuals story for it currently.

**Closed by bdellasc** 2017-03-20 14:05 UTC
Labels: request
