### ISSUE TITLE
VISUAL: Tree List.. Display of Relationships Representations

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#159] opened 2017-02-10 17:32 UTC
As a user I want to be able to understand the relationships and hierarchy of the parent child for the work item I have open.

VC's
* Visually represent and communicate the parent child relationship of the work item, in the list view, to communicate the hierarchy in the tree.
* Including visual feedback to support the rules of drag and drop, in the tree, of when an item in the list can't be dropped within the tree. Visually represent the can drop state, the can't drop state and the transitions visually.

**Comment by bdellasc** [comment] 2017-02-22 21:36
I think this is a duplicate of [Issue 133](https://github.com/fabric8io/fabric8-ux/issues/133). If so, I can close 133, as this has more detail in it.

**Comment by catrobson** [comment] 2017-02-24 12:59
+1 @bdellasc that this is a duplicate with #133 - you can close that issue.

**Comment by catrobson** [comment] 2017-04-12 19:27
Believe this is a duplicate of other work already completed.  Closing this issue.

**Closed by catrobson** 2017-04-12 19:27 UTC
Labels: visual design
