### ISSUE TITLE
FOLLOW UP: Filter Work Item List by Area

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ux#203] opened 2017-02-23 20:47 UTC
* Contact Dev, let them know you are their contact person for questions
* Check in with them, on an a periodic as needed basis throughout the sprint
* Assure that this functionality is demoed and meets specifications in the original UX design.

GitHub Issue:

UX
https://github.com/fabric8io/fabric8-ux/issues/158
https://github.com/fabric8io/fabric8-ux/issues/160

Dev
https://github.com/fabric8io/fabric8-planner/issues/914

**Comment by mindreeper2420** [comment] 2017-03-13 21:46
@Mgranfie @catrobson I think that the code for this has been merged into the Planner, so this can be closed?

**Comment by catrobson** [comment] 2017-03-14 02:33
@mindreeper2420 I'm not seeing all the filters built in correctly yet - I only see filter by assignee and it isn't working as designed yet.

**Comment by mindreeper2420** [comment] 2017-03-14 11:03
@catrobson looks like I jumped the gun last night - they are starting to be merged into the Planner this AM.

**Closed** 2017-03-23 13:29 UTC
